apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: mywebapp
    tier: frontend
spec:
  selector:
    app: mywebapp
    tier: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      name: task
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmapv4.0
data:
  BG_COLOR: "#12181b"
  FONT_COLOR: "#FFFFFF"
  CUSTOM_HEADER: "Limiting system resources!!!!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment1
  labels:
    app: mywebapp
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mywebapp
      tier: frontend
  template:
    metadata:
      labels:
        app: mywebapp
        tier: frontend
    spec:
      containers:
        - name: myimage
          image: devopsjourney1/mywebapp
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: myconfigmapv4.0
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"